# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.0
_src_path: https://github.com/napari/napari-plugin-template
display_name: Segmentation Gui
email: ananya.sundararajan@case.edu
full_name: Ananya Sundararajan
github_repository_url: https://github.com/Ananya-Sundararajan/seg-gui
github_username_or_organization: Ananya-Sundararajan
include_reader_plugin: true
include_sample_data_plugin: false
include_widget_plugin: true
include_writer_plugin: true
install_dependabot: true
install_precommit: true
license: MIT
module_name: seg_gui
plugin_name: seg-gui
short_description: A plugin that can be used to better validate and edit segmentation.
